version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 5
  rebase-strategy: disabled
