name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os:  ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go:  ["1.20"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    # TODO: enable testing in CI, currently blocked by ICMP requests in actions virtual environment
    # - run: "go test ./..."
    - run: "go mod tidy"
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.3"
        install-go: false
        # cache-key: ${{ matrix.go }}
