name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install semantic-release
        run: |
          npm install -D semantic-release

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - name: Show GoReleaser version
        run: goreleaser -v

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HONEYBADGER_API_KEY: ${{ secrets.HONEYBADGER_API_KEY }}
          NDT7_CLIENT_NAME: ${{ secrets.NDT7_CLIENT_NAME }}
          GIT_AUTHOR_NAME: imup-bot
          GIT_AUTHOR_EMAIL: support+imup-bot@imup.io
          GIT_COMMITTER_NAME: imup-bot
          GIT_COMMITTER_EMAIL: support+imup-bot@imup.io
        run: npx -p @semantic-release/changelog -p @semantic-release/exec -p @semantic-release/git semantic-release
