name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.2'
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install semantic-release
        run: |
          npm install -D semantic-release

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - name: Show GoReleaser version
        run: goreleaser -v

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_OAUTH_TOKEN }}
          GIT_AUTHOR_NAME: imup-bot
          GIT_AUTHOR_EMAIL: support+imup-bot@imup.io
          GIT_COMMITTER_NAME: imup-bot
          GIT_COMMITTER_EMAIL: support+imup-bot@imup.io
          GITHUB_TOKEN: ${{ secrets.GH_BOT_OAUTH_TOKEN }}
          HONEYBADGER_API_KEY: ${{ secrets.HONEYBADGER_API_KEY }}
          NDT7_CLIENT_NAME: ${{ secrets.NDT7_CLIENT_NAME }}
        run: npx -p @semantic-release/changelog -p @semantic-release/exec -p @semantic-release/git semantic-release --debug=true

      - name: Increment version and update installer scripts
        id: increment_version
        run: |
          # Get the latest release tag
          latest_tag=$(git describe --tags --abbrev=0)
          release_version=${latest_tag#v}
          remote_file="client_${release_version}_darwin_amd64.tar.gz"
          
          # Update the installer scripts with the new version and file name
          sed -i "s/^release_version=.*/release_version=\"${release_version}\"/" ./scripts/installers/*.sh
          sed -i "s/^remote_file=.*/remote_file=\"${remote_file}\"/" ./scripts/installers/*.sh
